services:
  postgres:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_USER: navadeep
      POSTGRES_DB: SeaWave
    networks:
      - db_net
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: controller
    environment:
      PGADMIN_DEFAULT_EMAIL: navadeep@gmail.com
      PGADMIN_DEFAULT_PASSWORD: "2005"
    ports:
      - "8000:80"
    networks:
      - db_net
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  db_net:
