services:
  postgres:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_USER: navadeep
      POSTGRES_DB: SeaWave
    networks:
      - db_net
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  keycloakdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keycloak
      POSTGRES_USER: navadeep
    networks:
      - db_net
    ports:
      - "5433:5433"
    command: ["postgres", "-p", "5433"]
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  keycloak:
    image: keycloak/keycloak:nightly
    environment:
      DB_VENDOR: POSTGRES
      DB_PASSWORD: root
      DB_USERNAME: navadeep
      DB_ADDR: keycloakdb
      DB_PORT: 5433
      DB_DATABASE: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8091:8080"
    depends_on:
      - keycloakdb
    command: ["start-dev", "--import-realm"]
  pgadmin:
    image: dpage/pgadmin4
    container_name: controller
    environment:
      PGADMIN_DEFAULT_EMAIL: navadeep@gmail.com
      PGADMIN_DEFAULT_PASSWORD: "2005"
    ports:
      - "8000:80"
    networks:
      - db_net
    depends_on:
      - postgres

  kafkaKeeper:
    image: confluentinc/cp-zookeeper:6.2.0  # Changed from 'zookeeper'
    container_name: kafkaZookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181  # Removed quotes
      ZOOKEEPER_TICK_TIME: 2000    # Changed from "3000" to 2000
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-broker:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka-kafka-broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      kafkaKeeper:
        condition: service_healthy
        
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'kafkaKeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8084:8080"
    depends_on:
      - kafka-broker
    environment:  # Added missing environment configuration
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:29092

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: kafka-schema-registry
    container_name: kafka-schema-registry
    depends_on:
      - kafka-broker
    ports:
      - "8083:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka-broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://kafka-schema-registry:8081

volumes:
  postgres_data:
  keycloak_data:

networks:
  db_net:
