services:
  postgres:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_USER: navadeep
      POSTGRES_DB: SeaWave
    networks:
      - db_net
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: controller
    environment:
      PGADMIN_DEFAULT_EMAIL: navadeep@gmail.com
      PGADMIN_DEFAULT_PASSWORD: "2005"
    ports:
      - "8000:80"
    networks:
      - db_net
    depends_on:
      - postgres
      
  kafkaKeeper:
    image: zookeeper
    container_name: kafkaZookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "3000"
  
  kafka_broker:
    image: confluentinc/cp-kafka
    container_name: kafka-kafka_broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - kafkaKeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'kafkaKeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:2902,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8084:8080"
    depends_on:
      - kafka_broker
  
  kafka-schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: kafka-schema-registry
    container_name: kafka-schema-registry
    depends_on:
      - kafka_broker
    ports:
      - "8083:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka_broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://kafka-schema-registry:8081
    
    



volumes:
  postgres_data:

networks:
  db_net:
